/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function (knex) {
  await knex('posts').insert([

    {
      description: `Had this bell for a while now, looking to give it away. Its a fantastic piece of art`,
      image: 'https://i.etsystatic.com/16762747/r/il/74f825/1457929538/il_fullxfull.1457929538_9gix.jpg',
      title: 'Vintage Bell',
      user_id: 1,
      location: 'Queens',
      category: 'Household',
      quantity: 1,
      weight: 30,
      length: 40,
      width: 70,
      height: 20,
      condition: 'New',
      pickup_type: 'drop-off',
      street_address: '111 South st',
      state: 'NY',
      zip_code: '12345'
    },
    {
      description: `I don't want to through this out if anyone is interested please reach out. First come first serve!`,
      image: 'https://girlinthegarage.net/wp-content/uploads/2017/11/IMG_8484-antique-highboy-before-1-1024x768.jpg',
      title: 'Old Dresser',
      user_id: 1,
      location: 'Brooklyn',
      category: 'Household',
      quantity: 1,
      weight: 50,
      length: 40,
      width: 70,
      height: 70,
      condition: 'Fair',
      pickup_type: 'arrange-pickup',
      street_address: '222 Bond st',
      state: 'NY',
      zip_code: '11122'
    },
    {
      description: `My friend gave me these but I don't have a table or paddles`,
      image: 'https://racketsportsworld.com/wp-content/uploads/2020/03/Table-Tennis-Balls.jpg?ezimgfmt=ng%3Awebp%2Fngcb1%2Frs%3Adevice%2Frscb1-2',
      title: 'Ping Pong Balls',
      user_id: 3,
      location: 'Bronx',
      category: 'Sporting',
      quantity: 1,
      weight: 1,
      length: 50,
      width: 20,
      height: 15,
      condition: 'Like-new',
      pickup_type: 'drop-off',
      street_address: '333 Perry st',
      state: 'NY',
      zip_code: '34512'
    },
    {
      description: `Not working anymore, maybe some screen issues, anyone interested in it for spare parts?`,
      image: 'https://pixl.varagesale.com/http://s3.amazonaws.com/hopshop-image-store-production/66166606/5da37d37760a3c9c33b6b3cc8790e115.jpg?_ver=large_uploader_thumbnail&w=640&h=640&fit=crop&rot=-270&s=3ca5168d22bd9da059ba174831258b64',
      title: 'Ipod 4',
      user_id: 2,
      location: 'Bronx',
      category: 'Tech',
      quantity: 1,
      weight: 2,
      length: 10,
      width: 8,
      condition: 'Salvage',
      pickup_type: 'drop-off',
      street_address: '444 Monk st',
      state: 'NY',
      zip_code: '12311'
    },
    {
      description: `A few great reads. Twilight (The Twilight Saga, #1), The Catcher in the Rye, The Scarlet Letter, and more. Anyone interested in them please message me!`,
      image: 'https://cdn.elearningindustry.com/wp-content/uploads/2016/05/top-10-books-every-college-student-read-1024x640.jpeg',
      title: 'Some Books!',
      user_id: 2,
      location: 'Staten Island',
      category: 'Household',
      quantity: 5,
      weight: 10,
      condition: 'Fair',
      pickup_type: 'arrange-pickup',
      street_address: '54 Flatbush ave',
      state: 'NY',
      zip_code: '34512'
    },
    {
      description: `Had this shirt for a while now, never got a chance to wear it - too big. Size: XL`,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUpJemVTpWYmAvWQVILT0BJ1bKY_1Viy631w&usqp=CAU',
      title: 'Button Down',
      user_id: 1,
      location: 'Queens',
      category: 'Clothing',
      quantity: 1,
      weight: 1,
      length: 80,
      width: 80,
      condition: 'New',
      pickup_type: 'arrange-pickup',
      street_address: '104 Atlantic ave',
      state: 'NY',
      zip_code: '34512'
    },
    {
      description: `Just bought a new gaming keyboard, anyone want to grab this? Works good!`,
      image: 'https://i.ebayimg.com/images/g/3tQAAOSwGA1iiDMJ/s-l640.jpg',
      title: 'Keyboard',
      user_id: 3,
      location: 'Manhattan',
      category: 'Tech',
      quantity: 1,
      weight: 2,
      height: 50,
      condition: 'Like-new',
      pickup_type: 'drop-off',
      street_address: '52 Main st',
      state: 'NY',
      zip_code: '12132'
    },
    {
      description: `Used office mouse, still works`,
      image: 'https://apollo-singapore.akamaized.net/v1/files/89jkabvt5fy3-IN/image;s=850x0',
      title: 'Office Mouse',
      user_id: 4,
      location: 'Manhattan',
      category: 'Tech',
      quantity: 1,
      weight: 1,
      length: 20,
      width: 40,
      height: 50,
      condition: 'Salvage',
      pickup_type: 'arrange-pickup',
      street_address: '333 Broadway ave',
      state: 'NY',
      zip_code: '34512'
    },
    {
      description: `Anyone want these board games? I've used them like 2-4 times. Don't enjoy playing them anymore`,
      image: 'https://assets-prd.ignimgs.com/2022/05/12/classic-board-games-1652389030946.png?width=1280',
      title: 'Board games',
      user_id: 4, 
      location: 'Brooklyn',
      category: 'Gaming',
      quantity: 3,
      weight: 5,
      length: 40,
      width: 70,
      height: 50,
      condition: 'Like-new',
      pickup_type: 'drop-off',
      street_address: '54 Flatbush ave',
      state: 'NY',
      zip_code: '34512'
    },
    {
      description: `Some bike parts I accumulated working on my new bike. Anyone interested in any of this?`,
      image: 'https://townsquare.media/site/689/files/2018/02/Bike-Parts.jpg?w=630&q=75',
      title: 'Bike Parts',
      user_id: 4, 
      location: 'Manhattan',
      category: 'Sporting',
      quantity: 10,
      weight: 40,
      length: 40,
      width: 70,
      height: 50,
      condition: 'Salvage',
      pickup_type: 'arrange-pickup',
      street_address: '54 Flatbush ave',
      state: 'NY',
      zip_code: '34512'
    },
    {
      description: `I found these in the shed of my new house. I don't really use tools`,
      image: 'https://hips.hearstapps.com/pop.h-cdn.co/assets/16/04/1024x1365/gallery-1453963828-img-8079.JPG?resize=480:*',
      title: 'Wrenches',
      user_id: 2, 
      location: 'Manhattan',
      category: 'Household',
      quantity: 4,
      weight: 15,
      length: 40,
      width: 70,
      height: 50,
      condition: 'Salvage',
      pickup_type: 'arrange-pickup',
      street_address: '333 Broadway ave',
      state: 'NY',
      zip_code: '34512'
    },
    {
      description: `I don't like the way it looks but I would feel too guilty throwing it out. If anyone could take it off my hands, it would make me feel a lot better`,
      image: 'https://i.ebayimg.com/images/g/xIMAAOSwhBtfR2jb/s-l640.jpg',
      title: 'Vase',
      user_id: 2, 
      location: 'Manhattan',
      category: 'Household',
      quantity: 1,
      weight: 10,
      length: 40,
      width: 70,
      height: 50,
      condition: 'Like-new',
      pickup_type: 'drop-off',
      street_address: '555 Atlantis ave',
      state: 'NY',
      zip_code: '34512'
    },
  ]);
};
